# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  url: <%= ENV['DATABASE_URL'] %>
  host: <%= ENV['SKIPPR_DATABASE_HOST'] || 'localhost' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: jvlivn_development

test:
  <<: *default
  database: jvlivn_test

production:
  <<: *default
  database: jvlivn_production
  username: jvlivn
  password: <%= ENV['JVLIVN_DATABASE_PASSWORD'] %>
  encoding: unicode
