# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: jvlivn_test

production:
  <<: *default
  adapter: postgresql
  database: jvlivn_production
  username: jvlivn
  password: <%= ENV['JVLIVN_DATABASE_PASSWORD'] %>
  pool: 5
  encoding: unicode
