# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ActiveStorage::Blob::Analyzable; end
module ActiveStorage::Blob::Identifiable; end
module ActiveStorage::Variant; end
